version: '3.5'

services:
  api:
    build:
      context: .
      target: dev
    container_name: go_mysql_crud_api
    volumes:
      - ./:/go/src/github.com/go-mysql-crud
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=credentials.json
    - VIRTUAL_PORT=80
    - VIRTUAL_HOST=go-mysql-crud.docker.dev
    env_file:
      - configuration/env/dev.env
    ports:
      - 8181:8181
    depends_on:
      - db

  db:
    image: mysql:8.0.16
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: go_mysql_crud_db
    ports:
      - 3306:3306
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql
